### ISSUE TITLE
台灣華藏淨宗學會

### ISSUE THREAD

**Issue by hanwei1980** [cmonos/TAKETORI-JS#1]
製作者様、

初めまして、こちらは台灣華藏淨宗學會、非営利団体です、
私は韓維（カン　イ）、と申します、宜しくお願い致します。

ご製作したプログラムは、私たちに非常に役立つ、素晴らしいな商品だと思います。
私たちは、現在使用中にいくつかの細かい問題を発生しました。
中国のセミコロンを使用することは、シンボルの一部が正しく表示されない、
ディスプレイに正常に回転できない、それに関し非常に困っています。
お願いしたいのは、私たちには修正のお手伝い可能でしょうか、或は、その原因を教えて頂かないでしょうか。
お忙しいところ、恐縮とは存じますが、
何卒宜しくお願い致します。
![daa6e2da-2784-4602-9e97-1f7ee4dde3dd](https://cloud.githubusercontent.com/assets/1889245/6990603/4fcadd90-daa2-11e4-8249-6c15f18507f0.png)

**Comment by cmonos** [comment]
韓維様

はじめまして。
不具合のご指摘ありがとうございます。
ご丁寧に日本語で書いていただき、恐縮です。

繁体字フォントの指定に誤りがあったようです。
最新版で修正されております。
お手数かと存じますが、最新版に差し替えた上で、上記ご確認ください。

![2015-04-04 12 49 25](https://cloud.githubusercontent.com/assets/506595/6991352/8d955542-daca-11e4-9532-57c061152c14.png)

**Comment by hanwei1980** [comment]
製作者様

お世話になります。

早速ご返事いただき、誠に有難うございました。
この度はアップグレードし、記号の表示の問題を確実に解決しました、非常に感謝しております。
私は、IE，Google Chrome，Firefox，Safari等主要なブラウザを個々にテストしました、
mac、windowsオペレーティングシステムの下にChrome表示につきまして、まだ問題がある見たい、それ以外のブラウザは全部正常でした。

お忙しいところ、誠に恐縮ですが、もう一度見てもらえるでしょうか？

非常に使いやすい、素敵なプログラムを作って頂き、心より感謝及び尊敬をしております。
何卒宜しくお願い申し上げます。

韓維より
![e9e5dc69-650d-4385-b2c4-1528cf75761f](https://cloud.githubusercontent.com/assets/1889245/7004924/15fce2a2-dca5-11e4-9dc0-7b8758bfb867.png)
![be79642e-9331-49e3-8fb7-b2971c096087](https://cloud.githubusercontent.com/assets/1889245/7004925/15fd93f0-dca5-11e4-9b4e-7b9071a9db26.png)

**Comment by cmonos** [comment]
韓維様

ご指摘の問題は Chrome の writing-mode: vertical-rl の処理が、中国語の縦書きに十分に対応していないためと思います。

私には完全な繁体語環境がありませんので、テストできていませんが、中国語が指定されている時「：」と「；」を縦中横扱いで表示するよう変更しました。

最新版に差し替えてお試しいただけましたらと思います。

**Comment by hanwei1980** [comment]
製作者様

お世話になっております。
ようやく問題を解決しました、助かりました。
この度は、ご親切に指導して頂き、誠にありがたく感謝の気持ちでいっぱいで御座います。
今後とも御指導を賜りますよう何卒宜しくお願い申し上げます。

韓維より
